### ISSUE TITLE
Can't build on Windows

### ISSUE THREAD

**Issue by Belphemur** [skywinder/github-changelog-generator#340]
Because of this line:
https://github.com/skywinder/github-changelog-generator/blob/master/github_changelog_generator.gemspec#L15

You can't use the date command on windows, it's used to set the date of the system. Gem can't build this module on windows.

**Comment by olleolleolle** [comment]
Thanks for reporting this.

**Comment by olleolleolle** [comment]
`Date.today.to_s` - would that work for you?

**Comment by Belphemur** [comment]
I've never worked with Ruby. 
If the gem spec is in Ruby and Date.today.to_s is present in Ruby 2.2.X it should be working on Windows without problems.

**Comment by olleolleolle** [comment]
See #343

**Comment by skywinder** [comment]
Fixed in 11.1.6

**Comment by Belphemur** [comment]
The bug is still present. It seems Windows interpret the Date.today.iso8601 as the command date...
```
C:\Windows\System32>gem install github_changelog_generator
Building native extensions.  This could take a while...

ERROR:  Error installing github_changelog_generator:
        ERROR: Failed to build gem native extension.

    C:/Ruby22-x64/bin/ruby.exe -rubygems C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rake-10.4.2/bin/rake RUBYARCHDIR=C:/Ruby22-x64/lib/ruby/gems/2.2.0/extensions/x64-mingw32/2.2.0/github_changelog_generator-1.11.6 RUBYLIBDIR=C:/Ruby22-x64/lib/ruby/gems/2.2.0/extensions/x64-mingw32/2.2.0/github_changelog_generator-1.11.6
rake aborted!
Bundler::GemspecError: There was a Gem::InvalidSpecificationException while loading github_changelog_generator.gemspec:
invalid date format in specification: "The system cannot accept the date entered.\nEnter the new date: (dd-mm-yy)" from
  C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/github_changelog_generator-1.11.6/github_changelog_generator.gemspec:15:in `block in <main>'

Gem::InvalidSpecificationException: invalid date format in specification: "The system cannot accept the date entered.\nEnter the new date: (dd-mm-yy)"

(See full trace by running task with --trace)

rake failed, exit code 1

Gem files will remain installed in C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/github_changelog_generator-1.11.6 for inspection.
Results logged to C:/Ruby22-x64/lib/ruby/gems/2.2.0/extensions/x64-mingw32/2.2.0/github_changelog_generator-1.11.6/gem_make.out

C:\Windows\System32>Date.today.iso8601
The system cannot accept the date entered.
Enter the new date: (dd-mm-yy)
```

If as said in the pull request #343 Ruby don't need that parameter, can you remove it? After all not using it set it as TODAY which is what you were doing anyway.
