### ISSUE TITLE
github_changelog_generator/generator/generator_tags.rb:61:in `detect_since_tag': undefined method `[]' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by crucialfelix** [skywinder/github-changelog-generator#351]
I have no idea what its trying to tell me. Should this be throwing exceptions like this ?

```
Performing task with options:
{:tag1=>nil,
 :tag2=>nil,
 :date_format=>"%Y-%m-%d",
 :output=>"CHANGELOG.md",
 :base=>"HISTORY.md",
 :issues=>true,
 :add_issues_wo_labels=>true,
 :add_pr_wo_labels=>true,
 :pulls=>true,
 :filter_issues_by_milestone=>true,
 :author=>true,
 :unreleased=>true,
 :unreleased_label=>"Unreleased",
 :compare_link=>true,
 :enhancement_labels=>["enhancement", "Enhancement"],
 :bug_labels=>["bug", "Bug"],
 :exclude_labels=>
  ["duplicate",
   "question",
   "invalid",
   "wontfix",
   "Duplicate",
   "Question",
   "Invalid",
   "Wontfix"],
 :max_issues=>nil,
 :simple_list=>false,
 :verbose=>true,
 :header=>"# Change Log",
 :merge_prefix=>"**Merged pull requests:**",
 :issue_prefix=>"**Closed issues:**",
 :bug_prefix=>"**Fixed bugs:**",
 :enhancement_prefix=>"**Enhancements**",
 :git_remote=>"origin",
 :user=>"supercollider",
 :project=>"supercollider",
 :future_release=>"3.7.0",
 :exclude_tags=>
  "3.3,3.4branchpoint,3.6-branch-point,Version-3.2rc1,Version-3.2rc3,Version-3.2rc5,Version-3.2rc6,Version-3.4alpha,Version-3.4rc1,Version-3.5beta1,Version-3.5beta2,Version-3.5beta3,Version-3.5beta4,Version-3.5rc1,Version-3.5rc2,Version-3.5rc3,Version-3.6alpha1,Version-3.6alpha2,Version-3.6alpha3,Version-3.6beta1,Version-3.6beta2,Version-3.6beta3,Version-3.7.0-alpha0,Version-3.7.0-alpha1,Version-3.7.0-beta1,after-qt5,before-gui-redirects-removed,before-linux,before-linux-B,before-linux-C,before-qt5,gui-redirects-removed,initial-deploy,initial-deploy-2,pre-gui-review,pre-linux-1-0,release-3.1,start,validated-linux,release-3.1,pre-linux-1-0,pre-gui-review,before-linux-C,before-linux-B,before-linux,start,deploy,deploy2,deploy3,deploy4,initial-deploy-3,mac-fixed,deploy5,before-sclang.app",
 :token=>"hidden value"}

Found 75 tags
/Users/crucial/.rvm/gems/ruby-2.2.1/gems/github_changelog_generator-1.11.7/lib/github_changelog_generator/generator/generator_tags.rb:61:in `detect_since_tag': undefined method `[]' for nil:NilClass (NoMethodError)
	from /Users/crucial/.rvm/gems/ruby-2.2.1/gems/github_changelog_generator-1.11.7/lib/github_changelog_generator/generator/generator_tags.rb:79:in `filter_since_tag'
	from /Users/crucial/.rvm/gems/ruby-2.2.1/gems/github_changelog_generator-1.11.7/lib/github_changelog_generator/generator/generator_tags.rb:70:in `get_filtered_tags'
	from /Users/crucial/.rvm/gems/ruby-2.2.1/gems/github_changelog_generator-1.11.7/lib/github_changelog_generator/generator/generator_tags.rb:5:in `fetch_and_filter_tags'
	from /Users/crucial/.rvm/gems/ruby-2.2.1/gems/github_changelog_generator-1.11.7/lib/github_changelog_generator/generator/generator_generation.rb:7:in `compound_changelog'
	from /Users/crucial/.rvm/gems/ruby-2.2.1/gems/github_changelog_generator-1.11.7/lib/github_changelog_generator.rb:29:in `run'
	from /Users/crucial/.rvm/gems/ruby-2.2.1/gems/github_changelog_generator-1.11.7/bin/github_changelog_generator:4:in `<top (required)>'
	from /Users/crucial/.rvm/gems/ruby-2.2.1/bin/github_changelog_generator:23:in `load'
	from /Users/crucial/.rvm/gems/ruby-2.2.1/bin/github_changelog_generator:23:in `<main>'
	from /Users/crucial/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/crucial/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
```

Apparently parsing exclude_tags from the config file still doesn't work.  But even on the command line I get the same bug:

```
 :exclude_tags=>
  ["3.3",
   "3.4branchpoint",
   "3.6-branch-point",
   "Version-3.2rc1",
   "Version-3.2rc3",
   "Version-3.2rc5",
   "Version-3.2rc6",
   "Version-3.4alpha",
   "Version-3.4rc1",
   "Version-3.5beta1",
   "Version-3.5beta2",
   "Version-3.5beta3",
   "Version-3.5beta4",
   "Version-3.5rc1",
   "Version-3.5rc2",
   "Version-3.5rc3",
   "Version-3.6alpha1",
   "Version-3.6alpha2",
   "Version-3.6alpha3",
   "Version-3.6beta1",
   "Version-3.6beta2",
   "Version-3.6beta3",
   "Version-3.7.0-alpha0",
   "Version-3.7.0-alpha1",
   "Version-3.7.0-beta1",
   "after-qt5",
   "before-gui-redirects-removed",
   "before-linux",
   "before-linux-B",
   "before-linux-C",
   "before-qt5",
   "gui-redirects-removed",
   "initial-deploy",
   "initial-deploy-2",
   "pre-gui-review",
   "pre-linux-1-0",
   "release-3.1",
   "start",
   "validated-linux",
   "release-3.1",
   "pre-linux-1-0",
   "pre-gui-review",
   "before-linux-C",
   "before-linux-B",
   "before-linux",
   "start",
   "deploy",
   "deploy2",
   "deploy3",
   "deploy4",
   "initial-deploy-3",
   "mac-fixed",
   "deploy5",
   "before-sclang.app"]}

Found 75 tags
/Users/crucial/.rvm/gems/ruby-2.2.1/gems/github_changelog_generator-1.11.7/lib/github_changelog_generator/generator/generator_tags.rb:61:in `detect_since_tag': undefined method `[]' for nil:NilClass (NoMethodError)
	from /Users/crucial/.rvm/gems/ruby-2.2.1/gems/github_changelog_generator-1.11.7/lib/github_changelog_generator/generator/generator_tags.rb:79:in `filter_since_tag'
	from /Users/crucial/.rvm/gems/ruby-2.2.1/gems/github_changelog_generator-1.11.7/lib/github_changelog_generator/generator/generator_tags.rb:70:in `get_filtered_tags'
	from /Users/crucial/.rvm/gems/ruby-2.2.1/gems/github_changelog_generator-1.11.7/lib/github_changelog_generator/generator/generator_tags.rb:5:in `fetch_and_filter_tags'
	from /Users/crucial/.rvm/gems/ruby-2.2.1/gems/github_changelog_generator-1.11.7/lib/github_changelog_generator/generator/generator_generation.rb:7:in `compound_changelog'
	from /Users/crucial/.rvm/gems/ruby-2.2.1/gems/github_changelog_generator-1.11.7/lib/github_changelog_generator.rb:29:in `run'
	from /Users/crucial/.rvm/gems/ruby-2.2.1/gems/github_changelog_generator-1.11.7/bin/github_changelog_generator:4:in `<top (required)>'
	from /Users/crucial/.rvm/gems/ruby-2.2.1/bin/github_changelog_generator:23:in `load'
	from /Users/crucial/.rvm/gems/ruby-2.2.1/bin/github_changelog_generator:23:in `<main>'
	from /Users/crucial/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/crucial/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by silvestreh** [comment]
I believe I'm getting the same error…

```shell
/Library/Ruby/Gems/2.0.0/gems/github_changelog_generator-1.11.7/lib/github_changelog_generator/fetcher.rb:211:in `fetch_date_of_tag': undefined method `[]' for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/github_changelog_generator-1.11.7/lib/github_changelog_generator/generator/generator_tags.rb:29:in `get_time_of_tag'
	from /Library/Ruby/Gems/2.0.0/gems/github_changelog_generator-1.11.7/lib/github_changelog_generator/generator/generator_fetcher.rb:24:in `block (2 levels) in fetch_tags_dates'
```

But since I know jack about Ruby, I'm not exactly sure if it's the same.

**Comment by Aluxian** [comment]
I'm getting this too:

```
Found 14 tags
/Users/aluxian/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/github_changelog_generator-1.12.0/lib/github_changelog_generator/generator/generator_tags.rb:61:in `detect_since_tag': undefined method `[]' for nil:NilClass (NoMethodError)
	from /Users/aluxian/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/github_changelog_generator-1.12.0/lib/github_changelog_generator/generator/generator_tags.rb:79:in `filter_since_tag'
	from /Users/aluxian/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/github_changelog_generator-1.12.0/lib/github_changelog_generator/generator/generator_tags.rb:70:in `get_filtered_tags'
	from /Users/aluxian/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/github_changelog_generator-1.12.0/lib/github_changelog_generator/generator/generator_tags.rb:5:in `fetch_and_filter_tags'
	from /Users/aluxian/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/github_changelog_generator-1.12.0/lib/github_changelog_generator/generator/generator_generation.rb:7:in `compound_changelog'
	from /Users/aluxian/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/github_changelog_generator-1.12.0/lib/github_changelog_generator.rb:29:in `run'
	from /Users/aluxian/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/github_changelog_generator-1.12.0/bin/github_changelog_generator:4:in `<top (required)>'
	from /Users/aluxian/.rbenv/versions/2.2.2/bin/github_changelog_generator:23:in `load'
	from /Users/aluxian/.rbenv/versions/2.2.2/bin/github_changelog_generator:23:in `<main>'
```

**Comment by skywinder** [comment]
Fixed in #368

**Comment by filib** [comment]
@olleolleolle @skywinder would it be possible for this to be pushed up to `rubygems`? I'm still seeing this error in `1.12.1`.

**Comment by filib** [comment]
No, sorry, it's a different error. I'll open another issue.

**Comment by olleolleolle** [comment]
@filib Hugs and have a good weekend!
